### ISSUE TITLE
Dataset download

### ISSUE THREAD

**Issue by samiede** [VincentXWD/CreateGirlsMoe#3]
Hey! 
I've tried recreating the steps to download the dataset, but apparently the structure of the website has changed, such that the SQL query does not return anything. Can you make the dataset available otherwise, or do you know how to still attain it?

Regards!

**Comment by VincentXWD** [comment]
Thanks for your attention to my project.
Here is the SQL query raw HTML file. You can get this file from: https://drive.google.com/open?id=1rjrjPuqQzCRY04mpiL2d3abxuHjCm0jB
Then you can use [script](https://github.com/VincentXWD/CreateGirlsMoe/blob/master/src/dataset/Spider/getchu_get_urls.py#L47) and change the 47th line to the HTML file path in your disk. Then run this script.
After that, you shall use [getchu_get_raw_images.py](https://github.com/VincentXWD/CreateGirlsMoe/blob/master/src/dataset/Spider/getchu_get_raw_images.py) and then you will get the result images.

What's more, it's normal that there are no images return in some urls. You'll get reminds when the script find and download some images to your disk.

Feel free to ask any question. I'll help you recreate this work.

**Comment by samiede** [comment]
Hey! Sorry for the late answer, thank you very much for taking your time to help me out!
I will try to download the files today, you are of great help to me!

Amazing work :)

**Comment by samiede** [comment]
Hey Vincent, thanks again for your help, it worked flawlessly! I had to remove the proxies in the download script for me, but other than that, it was just as described.

Am I correct that you also changed the architecture of the generator network? After the first 16 res blocks, there is one convolutional layer missing!

**Comment by VincentXWD** [comment]
Hello, Samiede,
Sorry for answering late. It seems that I forgot adding a convolutional layer. But I think that's OK. You can try to add it.

**Comment by samiede** [comment]
Hey Vincent, thanks for your answer! 
Yes, I've added it in my implementation, though I have problems with the generator: it only produces somewhat regular patterns of noise. It might be because I don't use the ResBlocks in the discriminator, as the implementation details for my use case does not permit Skip Connections for the discriminator. Maybe the discriminator is not able to provide the right feedback to the generator.
It also predicts the exact same probability for fake and real images. Maybe you have some insight on what I did wrong? The implementation of the GAN algorithm did work for me with the DCGAN networks, but the Resnet ones seem to get out of hand.

If you have the time and interest, here is the link to my repository
https://github.com/samiede/LRPGAN

Thank you very much for your time so far!

**Comment by VincentXWD** [comment]
Well done! Since I have a lot of work to do. So maybe I don't have much time going through your work. As you mentioned that you got noise from G. Maybe it caused by model collapsing. Please find some tricks to solve this kind of problem.
I'm not good at solving this kind of problems because I'm a newbie in this area haha.

**Comment by samiede** [comment]
Alright, I understand :)
Yes me too, it's the first time working with GANs for me, so interpreting failure is not easy!
Thank you for your time! 👍

**Comment by VincentXWD** [comment]
I'm happy to help! Good luck!

**Comment by yangzhikai** [comment]
could you put some image and conditional code as demo. The dataset is too big to download in a moment.

**Comment by VincentXWD** [comment]
> could you put some image and conditional code as demo. The dataset is too big to download in a moment.

Please open a new issue since this issue is already closed.

**Comment by Keysmis** [comment]
@samiede Hi~, when i download the dataset, i get error in https://github.com/VincentXWD/create-girls-moe-pytorch/issues/7 
Do you face that problems before? and how do you solve it ?
I wonder if you could provide your downloaded dataset to me? I will be very appreciate~
