### ISSUE TITLE
Model collapsed

### ISSUE THREAD

**Issue by yangzhikai** [VincentXWD/CreateGirlsMoe#5]
用小点训练集结果还看得下去，用大一点的连图像都没有了。我准备试试WGAN的loss,看行不行。

**Comment by yangzhikai** [comment]
@yangzhikai There are 19,000 data sets in my data set. At the beginning of training, there are no images until 4100 iteration.  When iteration reaches 6000iteration, there are clear results with faces.  I'm too quick to comment on models.

**Comment by VincentXWD** [comment]
Well done. I think you can check some tricks about how to train a GAN (for [example](https://www.kaggle.com/c/generative-dog-images/discussion/98595)). I'm not familiar with training a GAN and do not have more time doing research on it, so maybe I don't have the ability to answer your training questions now.
