### ISSUE TITLE
Is this article from NIPS2017?

### ISSUE THREAD

**Issue by yangzhikai** [VincentXWD/CreateGirlsMoe#6]
I'm quoting this article and it doesn't seem to be NIPS2017. Because there was no NIPS when I used baidu academic and Google academic search. Where can I see if it is NIPS2017?

**Comment by VincentXWD** [comment]
You can check author's page: http://yanghuaj.org . This paper "Towards the Automatic Anime Characters Creation with Generative Adversarial Networks" is published in NIPS 2017 Workshop on Machine Learning for Creativity and Design.
