### ISSUE TITLE
Dataset download error

### ISSUE THREAD

**Issue by Keysmis** [VincentXWD/CreateGirlsMoe#7]
hello~ , thanks for your great work
but i have some problems in downloading the cartoon image,
when i run the getchu_get_raw_images.py with proxies like:
![image](https://user-images.githubusercontent.com/9586803/82744498-eed31200-9dab-11ea-9641-a47888a40eb6.png)
i got connection refused error
and when i run the getchu_get_raw_images.py without proxies like:
![image](https://user-images.githubusercontent.com/9586803/82744512-1cb85680-9dac-11ea-96c7-6d4122a241af.png)
i got no error in code, but there is no images have been downloading~, i check the image url like:
![image](https://user-images.githubusercontent.com/9586803/82744522-43768d00-9dac-11ea-89d8-0ce4ddcf0335.png)
i got the error in web page like :
![image](https://user-images.githubusercontent.com/9586803/82744531-643ee280-9dac-11ea-8a75-49df5a45395e.png)
So, i could not download the image now~, could you have a look at this problem and do you have some solutions? I will be very appreciate~

**Comment by VincentXWD** [comment]
Hello,

It seems there were no characters' introduction in every selling page. Perhaps the website removed this piece of codes and set all characters' set those images as private.

**Comment by Keysmis** [comment]
@VincentXWD 
I got the error like:
![image](https://user-images.githubusercontent.com/9586803/82745217-51c8a700-9db4-11ea-9365-9b68fb8507b2.png)
Do you have any solutions? or Could you provided the dataset you download to me? I will be very appreciate!

**Comment by VincentXWD** [comment]
Hello @Keysmis,

That means you don't have the permission to access the resource. And I don't have these images in any of my devices. Maybe you can ask people who raised [issues](https://github.com/VincentXWD/create-girls-moe-pytorch/issues?q=is%3Aissue+is%3Aclosed) for help.

Thanks for your attention to this project. I'll also try to fix this problem when I have enough time.


> @VincentXWD
> I got the error like:
> ![image](https://user-images.githubusercontent.com/9586803/82745217-51c8a700-9db4-11ea-9365-9b68fb8507b2.png)
> Do you have any solutions? or Could you provided the dataset you download to me? I will be very appreciate!
